---
title: Git ommix
---

# Initalisation

```{r init, echo = F, warning = F, error = F, message = F}
library(tidyverse)
library(knitr)
library(git2r)

opts_chunk$set(echo = F,
               message = F,
               warning = F)

options(DT.options = list(dom = "Bfrtip",
                          buttons = c("copy", "csv", "excel", "pdf", "print"),
                          paging = F,
                          info = F,
                          search = F,
                          fixedHeader = T))
```

# Open repo

```{r open repo}
repository("grand") -> repo
```

# Helpers

## Get branches

```{r branches}
listBranches <- function(repo)
{
  repo %>%
    branches %>%
    names %>%
    setdiff(c("master", "git-annex"))
}
```

## Get commits

```{r commits}
listAllCommits <- function(repo)
 {
   repo %>%
     listBranches %>%
     map(~commits(repo, reverse = T, ref = .))
 }

repo %>%
  listBranches

repo %>%
  listAllCommits
```

# Git ommix commands

## List samples

```{r list samples}
listSamples <- listBranches

repo %>%
  listSamples
```

## Up-to-date result at the time of a sample

```{r uptodate of sample}
sampleResult <- function(repo, sample)
{
  repo %>%
    checkout(branch = sample)
  repo %>% commits(n = 1)
}

repo %>%
  sampleResult("1807_S20")
```

## Up-to-date result from a sample

```{r uptodate from sample/commit}
repo %>%
  checkout()
```
